/*
Choose Enrage version
*/


OUTER_TEXT_SPRINT kitid ~d2mk1~
OUTER_TEXT_SPRINT kitname ~KENSAIZERKER~
INCLUDE ~%install%/variables.tph~

//custom Enrage (copy backup)
ACTION_IF (enrage_mode = 1) BEGIN
  COPY_EXISTING ~%m1%.SPL~  ~override/%s1%.SPL~
END

//base game Enrage (copy SPCL321.spl)
ACTION_IF (enrage_mode = 2) BEGIN
  COPY_EXISTING ~SPCL321.SPL~  ~override/%s1%.SPL~
    LPF ALTER_EFFECT INT_VAR silent=1 STR_VAR match_resource=SPCL321 resource=~%s1%~ END
END


//
//